### ISSUE TITLE
A problem with ROW-0

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#2]
Hi,
Thanks for the great work with this repo!

I was experimenting a bit, but ran into an issue that I do not understand.
I created a simple domain and the problem to illustrate the issue: a robot that can move one step to the right and needs to go from (x1,y1) to (x5, y1).

My `domains/test/domain.pddl` file looks like this

> (define (domain test-domain)
  (:requirements :typing :action-costs :equality :adl)
  (:types
        direction - object
        coordinate - integer
  )
  (:predicates 
     (robot-at ?x ?y - coordinate)
     (succ ?x ?y - coordinate)
  )
  (:functions
     (total-cost) - number
  )
(:action move
    :parameters (?x1  ?y1 ?x2 ?y2 - coordinate)
    :precondition (and (robot-at ?x1 ?y1) (succ ?x1 ?x2) (= ?y1 ?y2))               
    :effect (and (robot-at ?x2 ?y2) (not (robot-at ?x1 ?y1)) (increase (total-cost) 1)))

My `domains/test/problem.pddl` file looks like this

> (define
	(problem
		test_problem
	)
	(:domain
		test-domain
	)
	(:objects
		x1 - coordinate
		x2 - coordinate
		x3 - coordinate
		x4 - coordinate
		x5 - coordinate		
		y1 - coordinate		
	)
	(:init
		(robot-at x1 y1)
                (succ x1 x2)
		(succ x2 x3)
		(succ x3 x4)
		(succ x4 x5)
		(= (total-cost) 0)
	)
	(:goal (and (robot-at x5 y1)))
	(:metric minimize (total-cost))
)

Finally, my configuration file looks like this

> PLPR
bin/compile
domains/test/domain.pddl
domain.pddl ins.pddl
0
5 10 1 domains/test/problem.pddl
5 10 domains/test/problem.pddl
0
0
1 1
0 0 0

After running the code, I get the following message in `ins.pddl`: _Unknown object ROW-0_

Given that ROW-0 is not an object in my problem definition, I suspected that must be instantiating possible places for goto commands. I managed to trace it down to the file [TypeGround.cpp](https://github.com/aig-upf/automated-programming-framework/blob/0b59dad004eda3db91558ea311d9b7746d213c8b/universal-pddl-parser/parser/TypeGround.cpp), but I don't understand what went wrong there.

This does not happen for your existing domains. Could it be that I made some mistake defining the config file? Please, let me know if I can give you any more info about the issue

**Comment by jsego** [comment]
Hi @gergia ,

The domain simulates a Stack in which previous planning programs can be pushed and popped, and the main procedure is always at row-0 (which is one of the objects we add in our compilation).

First I found a missing parenthesis ')' at the end of the domain  (probably because of copy&paste).

Then, in the configuration file, the training is correct `5 10 1 domains/test/problem.pddl`, but the test is wrong.
It should be  `1 10 domains/test/problem.pddl`, which means "test the generated planning program in 1 instance within 10 seconds (timeout), and the instance is domains/test/problem.pddl".

You can also play generating different programs, e.g. training with `2 10 1 domains/test/problem.pddl`, which will generate a solution to your problem generating a non-deterministic planning program of two lines:
```
0. move(?x1 ?y1 ?x2 ?y2)
1. goto( 0, !at(x5,y1) )
2. end
```

Best,
Javi

**Comment by ivan-gavran** [comment]
Great, thanks for the example and the explanation. Closing the issue :)
