### ISSUE TITLE
Weird behavior with a disjunction in precondition

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#3]
Hi, 
I ran into a weird behavior when an action's precondition is specified using a disjunction. To illustrate, I created a domain where the agent can move left or right. The problem instance has three fields ( [x1, y1], [x2, y1], [x3, y1]), the agent starts from [x1,y1] and the goal is to reach [x3, y1].

When I use a domain with two separate actions defined (move-left and move-right), everything works as expected and the plan consisting of two moves to the right is created. For the reference, here are the domain, problem instance and resulting program  files: 
[domainTwoDifferentActions.pddl.txt](https://github.com/aig-upf/automated-programming-framework/files/5621377/domainTwoDifferentActions.pddl.txt), [problem.pddl.txt](https://github.com/aig-upf/automated-programming-framework/files/5621381/problem.pddl.txt), [programTwoDifferentActions.txt](https://github.com/aig-upf/automated-programming-framework/files/5621382/programTwoDifferentActions.txt)
(I had to add a .txt extension for github to allow uploading. Pls remove upon download)

However, I could model the same two moves by a single action `move (?xA, ?xB)`. There, the precondition is that either ?xB is a successor of ?xA (`succ(?xA ?xB`) or that ?xA is a successor of ?xB (`succ(?xB ?xA`). In both cases, the effect should be that the agent changes its position to [?xB ?yB]. The resulting program here is confusing: it suggests first moving from [x1,y1] to [x2, y1] and then moving back from [x2. y1] to [x1,y1]. Attaching the domain file and the resulting program (the used problem instance is the same as in the modeling with two actions).
[domainDisjunctionInPrecondition.pddl.txt](https://github.com/aig-upf/automated-programming-framework/files/5621438/domainDisjunctionInPrecondition.pddl.txt)
[programDisjunctionInPrecondition.txt](https://github.com/aig-upf/automated-programming-framework/files/5621439/programDisjunctionInPrecondition.txt)

For sanity check, I tested the same setup with a regular planner (Metric-ff in this case), I got the correct plan back.

For completeness, I am attaching the configuration files used to run the tests 
[confDisjunctionInPrecondition.txt](https://github.com/aig-upf/automated-programming-framework/files/5621458/confDisjunctionInPrecondition.txt)
[confTwoDifferentActions.txt](https://github.com/aig-upf/automated-programming-framework/files/5621459/confTwoDifferentActions.txt)

What could be the reason for this behavior? Or am I reading the resulting program in a wrong way?

**Comment by jsego** [comment]
Hi @gergia ,

do not take into account the arguments that appear in the program.txt output file (that only means there is a valid assignment which makes the instruction to be applicable).
The only relevant data is the programmed instructions and their execution (repeats).
If we run FD with the "disjunction" domain I get the following plan:

program-move-0 x1 y1 x2 y1 row-0 (1001)
repeat-move-0-0 x1 y1 x2 y1 row-0 (1)
program-move-1 x2 y1 x1 y1 row-0 (1001)
repeat-move-0-1 x2 y1 x3 y1 row-0 (1)
program-end-2 row-0 (1)
repeat-end-main-0-2 row-0 (0)

That means: 
1) that we can program in the first line because we are in the first line, it is initially empty and there is some applicable move action; 
2) once the first line is programmed we apply the  (move x1 y1 x2 y1) action and continue in the second line;
3) since the second line is empty we may program a new instruction, in this case another move action, which has at least one valid assignment that makes the action to be applicable, e.g. x2 y1 x1 y1.
4) now the second instruction is applied as a (move x2 y1 x3 y1) and move to the last line
5) in the last line we can only program an end instruction
6) apply the end instruction validating the goal condition.

As you can see, the only execution actions that  have been applied are (move x1 y1 x2 y1) and (move x2 y1 x3 y1) which is the expected behavior.

I hope this helps.

**Comment by ivan-gavran** [comment]
Thanks, this indeed helps (and sorry for responding this late, I missed the response and only saw it once you closed the issue).
