### ISSUE TITLE
Conditional effects

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#4]
Hi,

I was a bit confused by wording in the README saying that 

>  more complicated constructs (such as `forall` and `when`) currently have to be implemented manually.

In particular, I am interested in `when`: what is meant by "implementing manually"? The broader context is [automated programming framework](https://github.com/aig-upf/automated-programming-framework), where I am trying to model an action that needs to have conditional effects.
If there is any way to get conditional effects working in that context, please suggest what one should do.

**Comment by jsego** [comment]
Hi @gergia ,

This relates to the Universal PDDL Parser (UPP). 
This just means that using the UPP as a library in a framework needs of some engineering efforts to create forall and when objects. If your intention is to use a PDDL domain with foralls and whens in the action schemata, then there is no problem, since it can parse them well. Otherwise, if you want to implement some code using the UPP, then we can go into the details of the implementation.

**Comment by ivan-gavran** [comment]
Hi @jsego , thanks for the answer. 
To explain where my confusion came from: I think I made a different syntactic error, and then was misguided by that README sentence to think that it must be the `when`. Now I got it to work properly.
