### ISSUE TITLE
Problems when running on multiple problem instances (e.g. robotics/mgo)

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#6]
Hi,

I am trying infer a generalized program for two problems simultaneously. To that end, I updated the config file to include two problem instance files. The relevant line in the config file looks like this
` 4 360 2 domains/karel/problem1-hoc.pddl domains/karel/problem2-hoc.pddl` (the full file is [here](https://github.com/gergia/automated-programming-framework/blob/multipleProblemsInstancesIssue/config/karel/karel-hoc.txt))

However, upon running, I get a parsing error
> terminate called after throwing an instance of 'parser::pddl::ExpectedToken'
  what():  ( expected
Aborted (core dumped)

This is confusing, since both of these problem instances individually can be parsed successfully.
In order to determine what the problem is, I looked into some of the examples in the repo that run their code on multiple problem instances. The same thing happens for some of them (`robotics/mgo.txt`, `robotics/tidying_up_5_0.txt`), but not for all (e.g., `jair17/dfs_4_3.txt`). I can not figure out what makes a difference, either in the config files or in the .pddl files.

Do you know what might be a problem?

**Comment by jsego** [comment]
Hi,

The issue in this case is that domains/karel/problem2-hoc.pddl does not exist.
The list of problems in that folder are:
- problem.pddl
- problem-hoc.pddl
- problem1-hoc.pddl

If the config goes with problem-hoc.pddl and problem1-hoc.pddl (instead of problem1-hoc and problem2-hoc), there is another issue where predicate (free-in-front) must be removed from problem-hoc.pddl. However, after testing in these problems there is something not supported by the framework which are functions from multiple instances, even if the function is the same. Functions like total-cost are not very relevant for planning when the cost of applying actions are uniform, if you look for optimal plans then an optimal planner will do the job, e.g in FD use the following planner ``--alias seq-opt-lmcut``.

**Comment by ivan-gavran** [comment]
Hi @jsego , thanks for the answer.
After removing the `total-cost` function, everything worked as expected. 

However, in case I wanted to work with different costs for different actions: I did not understand the suggestion in the last sentence. That is, where should I add `--alias seq-opt-lmcut`?

**Comment by jsego** [comment]
Hi @gergia,

Right now the planner is the first iteration of lama, and ``--alias seq-opt-lmcut`` is just an optimal planner in Fast-Downward to get optimal solutions. Since the ``total-cost`` was increased by 1 in your domain, all actions had uniform costs and this is equivalent to minimizing the length of the plan which is a common metric in the planning community.

You can modify the planner in the [``scripts/planners/planner.sh``](https://github.com/aig-upf/automated-programming-framework/blob/6299c12f063d1ab1bd3c445743fb286eb05f82ca/scripts/planners/planner.sh) file, updating the ``fd_planner`` variable, i.e. ``fd_planner=' --alias seq-opt-lmcut '``.

**Comment by ivan-gavran** [comment]
Thanks for the clarification!
